# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: mlb-pitcher-dashboard
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8501:8501"
    environment:
      - DB_PATH=/app/data/mlb_pitchers.db
      - PYTHONPATH=/app
    command: streamlit run src/app.py

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: mlb-pitcher-tests
    volumes:
      - .:/app
      - ./data:/app/data
      - ./test-results:/app/test-results
    environment:
      - DB_PATH=/app/data/test_mlb_pitchers.db
      - PYTHONPATH=/app
      - TEST_DB_PATH=/app/data/test.db
    command: ./run_tests.sh --all --coverage

  unit-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: mlb-pitcher-unit-tests
    volumes:
      - .:/app
      - ./data:/app/data
      - ./test-results:/app/test-results
    environment:
      - DB_PATH=/app/data/test_mlb_pitchers.db
      - PYTHONPATH=/app
      - TEST_DB_PATH=/app/data/test.db
    command: ./run_tests.sh --unit

  integration-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: mlb-pitcher-integration-tests
    volumes:
      - .:/app
      - ./data:/app/data
      - ./test-results:/app/test-results
    environment:
      - DB_PATH=/app/data/test_mlb_pitchers.db
      - PYTHONPATH=/app
      - TEST_DB_PATH=/app/data/test.db
    command: ./run_tests.sh --integration