# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: mlb-pitcher-dashboard
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8501:8501"
    environment:
      - DB_PATH=/app/data/mlb_pitchers.db
      - PYTHONPATH=/app
    command: streamlit run src/app.py

  pytest:
    build: .
    container_name: mlb-pitcher-tests
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/mlb_pitchers.db
      - PYTHONPATH=/app