# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    
    - name: Lint with pylint
      run: |
        pylint --fail-under=7.0 src tests
    
    - name: Format check with black
      run: |
        black --check src tests
    
    - name: Import check with isort
      run: |
        isort --check-only --profile black src tests
    
    - name: Test with pytest
      run: |
        pytest -xvs --cov=src --cov-report=xml --cov-report=term tests/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t mlb-pitcher-dashboard:latest .
    
    - name: Test Docker image
      run: |
        docker run --rm mlb-pitcher-dashboard:latest python -c "import src"